name: Publish @cliengo/wisipoo to JSR
on:
  push:
    branches:
      - prod
    paths:
      - 'packages/wisipoo/**'
      - '.github/workflows/publish-wisipoo.yml'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: yarn && npx jsr publish
